services:
  app:
   image: node:20
   working_dir: /app
   volumes:
    - .:/app
   ports:
      - "8080:8080"
   environment:
       DATABASE_URL: "postgresql://user:123456@postgres:5432/db"
   depends_on:
      - postgres
   command: >
      sh -c "./wait-for-it.sh postgres:5432 -- npm run migrate:deploy && npm run generate && npx prisma db seed"


  postgres:
    image: postgres:15
    restart: on-failure
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: db
    volumes:
      - db_data:/var/lib/postgresql/data

  migrations:
    image: node:20
    volumes:
      - .:/app
    working_dir: /app
    environment:
      DATABASE_URL: "postgresql://user:123456@postgres:5432/db"
    depends_on:
      - postgres
    entrypoint: ["sh", "-c", "npm run migrate:deploy && npm run generate && npx prisma/seed.ts"]

volumes:
  db_data: