version: '3.9'
services:
  app:
    build:
      context: .
    ports:
      - "5432:5432"
    environment:
      DATABASE_URL: "postgresql://user:123456@db:5432/dbdriver"
    depends_on:
      - db

  db:
    image: postgres:15
    restart: on-failure
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: dbdriver
    volumes:
      - db_data:/var/lib/postgresql/data

  migrations:
    image: node:20
    volumes:
      - .:/app
    working_dir: /app
    environment:
      DATABASE_URL: "postgresql://user:123456@db:5432/dbdriver"
    depends_on:
      - db
    entrypoint: ["sh", "-c", "npx prisma migrate deploy && tsx prisma/seed.ts"]

volumes:
  db_data:
