services:
  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: shopperdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
